language: java

jdk:
    - openjdk6
    - openjdk7
    - oraclejdk7
    - oraclejdk8

env:
    global:
        - DIALEKT_PUBLISH_VERSION=openjdk7
        - DIALEKT_PUBLISH_BRANCH=develop
        - secure: nn8cGhLEc5aHWu3rtlxy/6O83+PaiWzPVtBNCz/CJC0c9TDFJ1Dmysicx8Mf+H6iAu8wqhWg4P3tTARtm+Za34UKyXBql7RFf0FI2NjjElzSSLuY2COIp5To1emufNarHWPINwXMpLBPwnNanMX8xpCOiOhXLzjwQcnBlY9ODvA=

install: ./travis/install.sh
script: ./travis/build.sh
after_success: ./travis/success.sh
