language: java

jdk:
    - openjdk6
    - openjdk7
    - oraclejdk7
    - oraclejdk8

env:
    global:
        - DIALEKT_PUBLISH_VERSION=openjdk7
        - DIALEKT_PUBLISH_BRANCH=develop
        - secure: FLS0PZ3QNCYAKAbvSCqOVjX3gPv1JIX3cVGNZM9kJtRrtBwh/ruSWlgRD/yHx+NGmAgL4lctAGk+TUvNly36FplYuBKUHbtCn67dzPu8NVj+pIwFpVpWkQYDRk22H3jBFSttHwFHaaQ0htJlEJCr0D/XugypG3/sflMtO1XOQpM=

install: ./travis/install.sh
script: ./travis/build.sh
after_success: ./travis/success.sh
